[CmdletBinding()]
param([string]$WorkspaceRoot,[string]$CandidatePath)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($WorkspaceRoot)){$WorkspaceRoot=Join-Path $PSScriptRoot '..\..\..'};$workspace=(Resolve-Path -LiteralPath $WorkspaceRoot -ErrorAction Stop).Path
Import-Module (Join-Path $workspace 'automation\release-e2e\modules\Candidate.psm1') -Force
$token=Get-WindowsTokenEvidence
if(-not[bool]$token.standardNonAdministratorToken){throw 'Standard-token self-test requires a genuinely non-administrator, non-elevated medium-integrity caller.'}
$fingerprint=Get-CandidateFingerprint -WorkspaceRoot $workspace -CandidatePath $CandidatePath
if([string]$fingerprint.privateSigningProfile -ne 'PRIVATE_SELF_SIGNED'-or-not $fingerprint.authenticode-or[string]$fingerprint.authenticode.status -ne 'PASS'){throw 'Standard-token evidence requires the exact signed candidate and valid private Authenticode evidence.'}
foreach($tuple in @([string]$fingerprint.gitCommit,[string]$fingerprint.shippingInputIdentity,[string]$fingerprint.releaseFingerprintId,[string]$fingerprint.toolingFingerprintId)){if($tuple -notmatch '^[0-9a-fA-F]{40}$|^[0-9a-fA-F]{64}$'){throw 'Candidate tuple is incomplete or malformed.'}}
$runId='standard-token-'+(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ')+'-'+[guid]::NewGuid().ToString('N').Substring(0,8);$runRelative="evidence/standard-token/$runId";$runDir=Join-Path $workspace ($runRelative.Replace('/','\'))
if(Test-Path -LiteralPath $runDir){throw "Standard-token evidence run already exists: $runId"};New-Item -ItemType Directory -Path $runDir -Force|Out-Null
$rawReport=Join-Path $runDir 'installer-self-test-raw.txt';$canonical=Join-Path $runDir 'standard-token-evidence.json'
$before=@(Get-ChildItem -LiteralPath ([IO.Path]::GetTempPath()) -Directory -Filter 'DevFleet-Setup-SelfTest-*' -ErrorAction SilentlyContinue|ForEach-Object FullName)
$result=Invoke-CandidateSelfTest -Fingerprint $fingerprint -ReportPath $rawReport
$after=@(Get-ChildItem -LiteralPath ([IO.Path]::GetTempPath()) -Directory -Filter 'DevFleet-Setup-SelfTest-*' -ErrorAction SilentlyContinue|ForEach-Object FullName);$residual=@($after|Where-Object{$_-notin$before});$failed=@($result.requiredChecks.GetEnumerator()|Where-Object{-not[bool]$_.Value})
if($result.exitCode-ne 0-or[string]$result.result-ne 'PASS'-or$failed.Count-ne 0-or$residual.Count-ne 0){throw "Signed candidate standard-token self-test failed: exit=$($result.exitCode); result=$($result.result); failedChecks=$(@($failed.Name)-join ','); residualScratch=$($residual.Count)."}
if(-not[bool]$result.token.standardNonAdministratorToken){throw 'Candidate self-test token evidence was not a standard non-administrator token.'}
function Write-AtomicJson([string]$Path,[object]$Value){$tmp="$Path.$([guid]::NewGuid().ToString('N')).tmp";try{[IO.File]::WriteAllText($tmp,(($Value|ConvertTo-Json -Depth 20)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false));Move-Item -LiteralPath $tmp -Destination $Path -Force}finally{Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue}}
$runnerRelative='automation/release-e2e/tests/Test-InstallerSelfTestStandardToken.ps1';$runnerPath=Join-Path $workspace ($runnerRelative.Replace('/','\'))
$required=[ordered]@{pass=([string]$result.result-eq'PASS');payloadExtraction=[bool]$result.requiredChecks.extraction;bootstrapEntrypoint=[bool]$result.requiredChecks.bootstrap;parameterContract=[bool]$result.requiredChecks.parameterContract;embeddedTarCount=[bool]$result.requiredChecks.embeddedTarCount;factoryResetBackupGate=[bool]$result.requiredChecks.factoryResetBackupGate;planSafety=[bool]$result.requiredChecks.planSafety;devfleetVersion=[bool]$result.requiredChecks.devfleet;installerVersion=[bool]$result.requiredChecks.installer;payloadSha=[bool]$result.requiredChecks.payloadSha}
$evidence=[ordered]@{schemaVersion=1;runId=$runId;status='PASS';standardNonAdministratorToken=$true;runDirectory=$runRelative;rawReportPath="$runRelative/installer-self-test-raw.txt";canonicalEvidencePath="$runRelative/standard-token-evidence.json";generatedAtUtc=(Get-Date).ToUniversalTime().ToString('o');candidateBuildCommit=[string]$fingerprint.gitCommit;repositoryHead=[string]$fingerprint.repositoryHead;shippingInputIdentity=[string]$fingerprint.shippingInputIdentity;releaseFingerprintId=[string]$fingerprint.releaseFingerprintId;toolingFingerprintId=[string]$fingerprint.toolingFingerprintId;exe=[ordered]@{sha256=[string]$fingerprint.candidate.sha256;bytes=[int64]$fingerprint.candidate.bytes};tar=[ordered]@{sha256=[string]$fingerprint.tar.sha256;bytes=[int64]$fingerprint.tar.bytes};runner=[ordered]@{path=$runnerRelative;sha256=(Get-FileHash -LiteralPath $runnerPath -Algorithm SHA256).Hash.ToLowerInvariant()};token=$result.token;exitCode=[int]$result.exitCode;reportSha256=[string]$result.reportSha256;requiredChecks=$required;residualSelfTestScratchCount=$residual.Count}
Write-AtomicJson $canonical $evidence
$pointer=Join-Path $workspace 'evidence\CURRENT-STANDARD-TOKEN.json';Write-AtomicJson $pointer $evidence
Set-ItemProperty -LiteralPath $rawReport -Name IsReadOnly -Value $true;Set-ItemProperty -LiteralPath $canonical -Name IsReadOnly -Value $true
$evidence|ConvertTo-Json -Depth 20
