$ErrorActionPreference='Stop'
$modulePath=Join-Path (Split-Path -Parent $PSScriptRoot) 'modules\MultipassDiagnostic.psm1'
Import-Module $modulePath -Force
$count=0
function Check([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message};$script:count++}

$pwsh=(Get-Process -Id $PID).Path
$deadline=[datetime]::UtcNow.AddSeconds(10)
$success=Invoke-DevFleetBoundedNativeProbe -Operation version -FilePath $pwsh -ArgumentList @('-NoProfile','-NonInteractive','-Command','[Console]::Out.Write("multipass 1.15.1")') -TimeoutSeconds 5 -OwnerDeadlineUtc $deadline
Check ($success.outcome -eq 'PASS' -and $success.stdout -eq 'multipass 1.15.1') 'bounded native collector did not preserve successful output'
$legacy=Invoke-DevFleetBoundedNativeProbe -Operation version -FilePath $pwsh -ArgumentList @('-NoProfile','-NonInteractive','-Command','[Console]::Out.Write("legacy argument path")') -TimeoutSeconds 5 -OwnerDeadlineUtc ([datetime]::UtcNow.AddSeconds(10)) -ForceLegacyArgumentString
Check ($legacy.outcome-eq'PASS'-and$legacy.stdout-eq'legacy argument path') 'Windows PowerShell legacy argument quoting changed the native probe contract'
$singlePath=@(Get-DevFleetExistingFilePathSet -CandidatePaths @('C:\fixture\multipass.exe') -PathExistsProvider {param($path)$true})
Check ($singlePath.Count-eq1-and$singlePath[0]-eq'C:\fixture\multipass.exe') 'production executable-path normalization unwrapped a singleton under StrictMode'
$nonzero=Invoke-DevFleetBoundedNativeProbe -Operation version -FilePath $pwsh -ArgumentList @('-NoProfile','-NonInteractive','-Command','[Console]::Error.Write("classified failure");exit 7') -TimeoutSeconds 5 -OwnerDeadlineUtc ([datetime]::UtcNow.AddSeconds(10))
Check ($nonzero.outcome -eq 'NONZERO' -and $nonzero.exitCode -eq 7 -and $nonzero.stderr -match 'classified failure') 'bounded native collector conflated a nonzero exit with absence'
$timer=[Diagnostics.Stopwatch]::StartNew();$timeout=Invoke-DevFleetBoundedNativeProbe -Operation version -FilePath $pwsh -ArgumentList @('-NoProfile','-NonInteractive','-Command','Start-Sleep -Seconds 20') -TimeoutSeconds 1 -OwnerDeadlineUtc ([datetime]::UtcNow.AddSeconds(3));$timer.Stop()
Check ($timeout.outcome -eq 'TIMEOUT' -and $timer.Elapsed.TotalSeconds -lt 8) 'bounded native collector did not terminalize a stuck child'
$expired=Invoke-DevFleetBoundedNativeProbe -Operation version -FilePath $pwsh -ArgumentList @('-NoProfile') -TimeoutSeconds 5 -OwnerDeadlineUtc ([datetime]::UtcNow.AddSeconds(-1))
Check ($expired.outcome -eq 'OWNER_EXPIRED') 'native collector revived an expired owner deadline'

$processScript=Get-DevFleetBoundedProcessScriptBlock
$scratchRoot=Join-Path (Split-Path -Parent $PSScriptRoot) ".tmp-multipass-process-$PID"
try {
    New-Item -ItemType Directory -Path $scratchRoot -Force|Out-Null
    $importWorker=Join-Path $scratchRoot 'import-worker.ps1'
    [IO.File]::WriteAllText($importWorker,"param([string]`$ModulePath)`nImport-Module `$ModulePath -Force -ErrorAction Stop`n[Console]::Out.Write((ConvertTo-DevFleetDiagnosticSafeText 'bounded-ok'))`n",[Text.UTF8Encoding]::new($false))
    $request=[ordered]@{filePath=$pwsh;arguments=@('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$importWorker,$modulePath);deadlineUnixMilliseconds=[DateTimeOffset]::new([datetime]::UtcNow.AddSeconds(10)).ToUnixTimeMilliseconds()}|ConvertTo-Json -Depth 4 -Compress
    $processSuccess=&$processScript $request
    Check ($processSuccess.outcome-eq'PASS'-and$processSuccess.stdout-eq'bounded-ok') 'bounded per-process worker did not deliver and import the hash-addressable module'
    $stuckWorker=Join-Path $scratchRoot 'stuck-worker.ps1'
    [IO.File]::WriteAllText($stuckWorker,"Start-Sleep -Seconds 20`n",[Text.UTF8Encoding]::new($false))
    $request=[ordered]@{filePath=$pwsh;arguments=@('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$stuckWorker);deadlineUnixMilliseconds=[DateTimeOffset]::new([datetime]::UtcNow.AddSeconds(1)).ToUnixTimeMilliseconds()}|ConvertTo-Json -Depth 4 -Compress
    $timer=[Diagnostics.Stopwatch]::StartNew();$processTimeout=&$processScript $request;$timer.Stop()
    Check ($processTimeout.outcome-eq'TIMEOUT'-and$timer.Elapsed.TotalSeconds-lt8) "bounded per-process worker did not stop its exact process tree at the inherited deadline (outcome=$($processTimeout.outcome); elapsed=$([math]::Round($timer.Elapsed.TotalSeconds,3)); deadline=$($processTimeout.deadlineUtc); error=$($processTimeout.stderr))"
} finally {if(Test-Path -LiteralPath $scratchRoot){Remove-Item -LiteralPath $scratchRoot -Recurse -Force}}

$fixtureRun="m1-worker-entry-$PID";$fixtureParent="C:\Users\Public\DevFleet-E2E\$fixtureRun";$fixtureRoot=Join-Path $fixtureParent 'M1';$fixturePrograms=Join-Path (Split-Path -Parent $PSScriptRoot) ".tmp-m1-worker-programs-$PID";$originalProgramFiles=$env:ProgramFiles;$originalProgramFilesX86=${env:ProgramFiles(x86)};$originalProgramData=$env:ProgramData
try {
    New-Item -ItemType Directory -Path $fixtureRoot,$fixturePrograms,(Join-Path $fixturePrograms 'Multipass\bin') -Force|Out-Null
    $fixtureModule=Join-Path $fixtureRoot 'MultipassDiagnostic.psm1';Copy-Item -LiteralPath $modulePath -Destination $fixtureModule
    $fakeMultipass=Join-Path $fixturePrograms 'Multipass\bin\multipass.exe';Copy-Item -LiteralPath (Get-Command cmd.exe).Source -Destination $fakeMultipass
    $env:ProgramFiles=$fixturePrograms;${env:ProgramFiles(x86)}=$fixturePrograms;$env:ProgramData=Join-Path $fixturePrograms 'ProgramData'
    $workerName="DevFleet-E2E-E-M1-$fixtureRun";$workerOwner=[datetime]::UtcNow.AddSeconds(30);$workerOperation=$workerOwner.AddSeconds(-10)
    $workerRequest=[ordered]@{runId=$fixtureRun;vmId='84b7d8b8-ee6c-4085-aa29-4b0adc316de2';payloadSha256=('a'*64);instanceName=$workerName;remoteRoot=$fixtureRoot;modulePath=$fixtureModule;ubuntuImage='24.04';expectedMultipassSha256=(Get-FileHash -LiteralPath $fakeMultipass -Algorithm SHA256).Hash.ToLowerInvariant();ownerDeadlineUnixMilliseconds=[DateTimeOffset]::new($workerOwner).ToUnixTimeMilliseconds();operationDeadlineUnixMilliseconds=[DateTimeOffset]::new($workerOperation).ToUnixTimeMilliseconds()}|ConvertTo-Json -Depth 6 -Compress
    $workerBase64=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($workerRequest));$entryWorker=Join-Path (Split-Path -Parent $PSScriptRoot) 'Invoke-CampaignEMultipassM1Worker.ps1'
    $workerOutput=@(& $pwsh -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $entryWorker -RequestBase64 $workerBase64 2>$null);$workerExit=$LASTEXITCODE;$durablePath=Join-Path $fixtureRoot 'm1-worker-result.json';$durable=Get-Content -LiteralPath $durablePath -Raw|ConvertFrom-Json
    Check ($workerExit-eq1-and[string]$durable.status-ceq'BLOCKED'-and[string]$durable.cleanup.instanceName-ceq$workerName-and[string]$durable.primaryError-cnotmatch'New-DevFleetCampaignEM1CleanupState') 'actual M1 worker entry did not import before cleanup construction or durably bind the validated identity'
} finally {
    $env:ProgramFiles=$originalProgramFiles;${env:ProgramFiles(x86)}=$originalProgramFilesX86;$env:ProgramData=$originalProgramData
    if((Test-Path -LiteralPath $fixtureParent)-and[IO.Path]::GetFullPath($fixtureParent).StartsWith('C:\Users\Public\DevFleet-E2E\',[StringComparison]::OrdinalIgnoreCase)){Remove-Item -LiteralPath $fixtureParent -Recurse -Force}
    if((Test-Path -LiteralPath $fixturePrograms)-and[IO.Path]::GetFullPath($fixturePrograms).StartsWith([IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot)),[StringComparison]::OrdinalIgnoreCase)){Remove-Item -LiteralPath $fixturePrograms -Recurse -Force}
}

$base=[datetime]'2026-09-06T18:00:00Z';$clock=$base
$environment={param($vm,$id,$candidate,$prefix)[ordered]@{computerName='E2E-L1';principal=[ordered]@{kind='ADMINISTRATOR';isAdministrator=$true};capacity=[ordered]@{logicalProcessors=4;totalMemoryBytes=16GB;freeMemoryBytes=12GB;systemDriveFreeBytes=100GB};nestedVirtualization=[ordered]@{hyperVFeatureState='Enabled';vmMonitorModeExtensions=$true;secondLevelAddressTranslation=$true;virtualizationFirmwareEnabled=$true};multipass=[ordered]@{executableStatus='PRESENT';executablePresent=$true;executablePath='C:\Program Files\Multipass\bin\multipass.exe';sha256=('a'*64);fileVersion='1.15.1'};services=@([ordered]@{name='Multipass';state='Running';startMode='Auto';processId=42});backendInventory=[ordered]@{hyperV=[ordered]@{status='PASS';boundNames=@();foreignCount=0}};activeProduct=[ordered]@{activeTransactionPresent=$false;activeInstallProcessCount=0}}}
$probe={param($operation,$path,$args,$seconds,$owner) $script:clock=$script:clock.AddSeconds(1);$output=switch($operation){version{'multipass 1.15.1'}driver{'hyperv'}'privileged-mounts'{'false'}inventory{'{"list":[]}'}image{'Image 24.04 Ubuntu'}};[pscustomobject]@{operation=$operation;outcome='PASS';exitCode=0;startedAtUtc=$script:clock.AddMilliseconds(-100).ToString('o');finishedAtUtc=$script:clock.ToString('o');deadlineUtc=([datetime]$owner).ToUniversalTime().ToString('o');stdout=$output;stderr='';pid=42;outputComplete=$true;stdoutTruncated=$false;stderrTruncated=$false}}
$events={param($owner)[ordered]@{status='PASS';records=@([ordered]@{provider='Multipass';eventId=1;level='Error';timestampUtc='2026-09-06T17:59:00Z';category='SERVICE'})}}
$snapshot=Get-DevFleetMultipassM0Snapshot -RunId 'e-m0-unit' -ExpectedVmName 'DevFleet-E2E-Win11-01' -ExpectedVmId ([guid]'84b7d8b8-ee6c-4085-aa29-4b0adc316de2') -UbuntuImage '24.04' -CandidateInstanceNames @('devfleet-primary','devfleet-failover','devfleet-vault') -RunOwnedPrefix 'DevFleet-E2E-E-unit' -OwnerDeadlineUtc $base.AddMinutes(2) -EnvironmentProvider $environment -NativeProbeProvider $probe -EventProvider $events -ClockProvider {$script:clock} -PrimaryError 'password=do-not-store'
Check (Assert-DevFleetMultipassM0Snapshot -Snapshot $snapshot -ExpectedRunId 'e-m0-unit' -ExpectedVmName 'DevFleet-E2E-Win11-01' -ExpectedVmId ([guid]'84b7d8b8-ee6c-4085-aa29-4b0adc316de2')) 'valid production collector snapshot was rejected'
Check ($snapshot.status -eq 'COMPLETE' -and $snapshot.primaryError -eq 'password=<redacted>') 'collector did not preserve and redact the primary error'
Check ((@($snapshot.probes|Where-Object operation -eq inventory)[0].data.foreignCount) -eq 0) 'collector inventory normalization failed'

$wrongRun=$snapshot|ConvertTo-Json -Depth 24|ConvertFrom-Json;$wrongRun.runId='wrong';$rejected=$false;try{Assert-DevFleetMultipassM0Snapshot -Snapshot $wrongRun -ExpectedRunId 'e-m0-unit' -ExpectedVmName 'DevFleet-E2E-Win11-01' -ExpectedVmId ([guid]'84b7d8b8-ee6c-4085-aa29-4b0adc316de2')|Out-Null}catch{$rejected=$true};Check $rejected 'collector accepted a wrong run identity'
$wrongVm=$snapshot|ConvertTo-Json -Depth 24|ConvertFrom-Json;$wrongVm.expectedVmId=[guid]::NewGuid().ToString();$rejected=$false;try{Assert-DevFleetMultipassM0Snapshot -Snapshot $wrongVm -ExpectedRunId 'e-m0-unit' -ExpectedVmName 'DevFleet-E2E-Win11-01' -ExpectedVmId ([guid]'84b7d8b8-ee6c-4085-aa29-4b0adc316de2')|Out-Null}catch{$rejected=$true};Check $rejected 'collector accepted a wrong VM identity'
$late=$snapshot|ConvertTo-Json -Depth 24|ConvertFrom-Json;$late.producedAtUtc='2026-09-06T18:03:00Z';$rejected=$false;try{Assert-DevFleetMultipassM0Snapshot -Snapshot $late -ExpectedRunId 'e-m0-unit' -ExpectedVmName 'DevFleet-E2E-Win11-01' -ExpectedVmId ([guid]'84b7d8b8-ee6c-4085-aa29-4b0adc316de2')|Out-Null}catch{$rejected=$true};Check $rejected 'collector accepted a result first produced after its immutable deadline'
$overlap=$snapshot|ConvertTo-Json -Depth 24|ConvertFrom-Json;$overlap.probes[1].startedAtUtc=$overlap.probes[0].startedAtUtc;$rejected=$false;try{Assert-DevFleetMultipassM0Snapshot -Snapshot $overlap -ExpectedRunId 'e-m0-unit' -ExpectedVmName 'DevFleet-E2E-Win11-01' -ExpectedVmId ([guid]'84b7d8b8-ee6c-4085-aa29-4b0adc316de2')|Out-Null}catch{$rejected=$true};Check $rejected 'collector accepted overlapping Multipass CLI probes'
$malformed=[pscustomobject]@{operation='inventory';outcome='PASS';exitCode=0;startedAtUtc=$base.ToString('o');finishedAtUtc=$base.AddSeconds(1).ToString('o');deadlineUtc=$base.AddMinutes(1).ToString('o');stdout='not-json';stderr=''}
$normalized=ConvertTo-DevFleetMultipassProbeObservation -Probe $malformed -UbuntuImage '24.04' -CandidateInstanceNames @('devfleet-primary') -RunOwnedPrefix 'DevFleet-E2E-E-unit'
Check ($normalized.outcome -eq 'MALFORMED') 'invalid Multipass JSON masqueraded as absence'
foreach($outcome in @('NONZERO','TIMEOUT','START_FAILED')){$raw=[pscustomobject]@{operation='inventory';outcome=$outcome;exitCode=if($outcome-eq'NONZERO'){9}else{$null};startedAtUtc=$base.ToString('o');finishedAtUtc=$base.AddSeconds(1).ToString('o');deadlineUtc=$base.AddMinutes(1).ToString('o');stdout='';stderr='token=redact-me'};$normalized=ConvertTo-DevFleetMultipassProbeObservation -Probe $raw -UbuntuImage '24.04' -CandidateInstanceNames @('devfleet-primary') -RunOwnedPrefix 'DevFleet-E2E-E-unit';Check ($normalized.outcome -eq $outcome -and $normalized.error -notmatch 'redact-me') "$outcome was not preserved and redacted"}

$absentEnvironment={param($vm,$id,$candidate,$prefix)[ordered]@{computerName='E2E-L1';principal=[ordered]@{kind='ADMINISTRATOR';isAdministrator=$true};capacity=[ordered]@{};nestedVirtualization=[ordered]@{};multipass=[ordered]@{executableStatus='ABSENT';executablePresent=$false;executablePath='';sha256='';fileVersion=''};services=@();backendInventory=[ordered]@{};activeProduct=[ordered]@{activeTransactionPresent=$false;activeInstallProcessCount=0}}}
$clock=$base;$absent=Get-DevFleetMultipassM0Snapshot -RunId 'e-m0-absent' -ExpectedVmName 'DevFleet-E2E-Win11-01' -ExpectedVmId ([guid]'84b7d8b8-ee6c-4085-aa29-4b0adc316de2') -UbuntuImage '24.04' -CandidateInstanceNames @('devfleet-primary') -RunOwnedPrefix 'DevFleet-E2E-E-absent' -OwnerDeadlineUtc $base.AddMinutes(1) -EnvironmentProvider $absentEnvironment -EventProvider $events -ClockProvider {$script:clock}
Check ($absent.status -eq 'COMPLETE' -and @($absent.probes|Where-Object outcome -eq 'SKIPPED_NO_EXECUTABLE').Count -eq 5) 'executable absence did not remain a complete positive environment observation'
$clock=$base;$partial=Get-DevFleetMultipassM0Snapshot -RunId 'e-m0-partial' -ExpectedVmName 'DevFleet-E2E-Win11-01' -ExpectedVmId ([guid]'84b7d8b8-ee6c-4085-aa29-4b0adc316de2') -UbuntuImage '24.04' -CandidateInstanceNames @('devfleet-primary') -RunOwnedPrefix 'DevFleet-E2E-E-partial' -OwnerDeadlineUtc $base.AddMinutes(1) -EnvironmentProvider $absentEnvironment -EventProvider {throw 'event token=redact-me'} -ClockProvider {$script:clock} -PrimaryError 'primary failure remains'
Check ($partial.status -eq 'PARTIAL' -and $partial.primaryError -eq 'primary failure remains' -and $partial.errors[0] -notmatch 'redact-me') 'partial collector failure suppressed the primary error or leaked diagnostics'

$m1Name='DevFleet-E2E-E-M1-unit';$script:m1Clock=$base;$script:m1Calls=[Collections.Generic.List[object]]::new();$infoJson='{"info":{"DevFleet-E2E-E-M1-unit":{"state":"Running","ipv4":["10.10.10.2"]}},"errors":[]}'
$m1Provider={param($operation,$path,$arguments,$seconds,$owner)$start=$script:m1Clock;$script:m1Clock=$script:m1Clock.AddSeconds(2);[void]$script:m1Calls.Add([pscustomobject]@{operation=$operation;arguments=@($arguments);seconds=$seconds;owner=([datetime]$owner).ToUniversalTime().ToString('o')});$stdout=if($operation-like'info-*'){$infoJson}elseif($operation-eq'cloud-init'){'status: done'}else{''};[pscustomobject]@{operation=$operation;outcome='PASS';exitCode=0;pid=55;startedAtUtc=$start.ToString('o');finishedAtUtc=$script:m1Clock.ToString('o');deadlineUtc=([datetime]$owner).ToUniversalTime().ToString('o');stdout=$stdout;stderr='';outputComplete=$true}}
$m1=Invoke-DevFleetCampaignEMultipassM1Sequence -RunId 'unit' -InstanceName $m1Name -UbuntuImage '24.04' -MultipassPath 'C:\fixture\multipass.exe' -OwnerDeadlineUtc $base.AddMinutes(15) -NativeProbeProvider $m1Provider -ClockProvider {$script:m1Clock}
Check ([string]$m1.status-ceq'PASS'-and[bool]$m1.progress.launchAccepted-and[bool]$m1.progress.instanceRunning-and[bool]$m1.progress.ipObserved-and[bool]$m1.progress.sshReady-and[bool]$m1.progress.cloudInitDone) 'M1 production sequence did not distinguish launch, IP, SSH and cloud-init completion'
Check ((@($script:m1Calls[0].arguments)-join'|')-ceq"launch|24.04|--name|$m1Name|--cpus|2|--memory|2G|--disk|10G") 'M1 production sequence did not construct the exact modest-resource plain launch'
Check ((@($script:m1Calls[2].arguments)-join'|')-ceq"exec|$m1Name|--|true"-and(@($script:m1Calls[3].arguments)-join'|')-ceq"exec|$m1Name|--|cloud-init|status|--wait") 'M1 production sequence did not exercise real SSH/cloud-init readiness without product inputs'
Check (@($script:m1Calls|Where-Object{$_.owner-cne'2026-09-06T18:15:00.0000000Z'}).Count-eq0-and@($m1.observations).Count-eq5) 'M1 production sequence granted a fresh child deadline or lost operation cardinality'
Check (-not[bool]$m1.productLifecycleStarted-and-not[bool]$m1.productProgressClaimed-and($m1|ConvertTo-Json -Depth 16)-notmatch'10.10.10.2') 'M1 production sequence fabricated product progress or retained guest address output'

$cleanupState=New-DevFleetCampaignEM1CleanupState -InstanceName $m1Name
Check ([string]$cleanupState.instanceName-ceq$m1Name-and[string]$cleanupState.status-ceq'UNVERIFIED'-and[int]$cleanupState.finalInventoryCount-eq-1) 'M1 cleanup producer did not bind the validated launch identity'
$invalidCleanupRejected=$false;try{New-DevFleetCampaignEM1CleanupState -InstanceName 'devfleet-primary'|Out-Null}catch{$invalidCleanupRejected=$true};Check $invalidCleanupRejected 'M1 cleanup producer accepted a product or non-run-owned identity'
$cleanupState.status='ABSENT_VERIFIED';$cleanupState.finalInventoryCount=0
$validM1=[pscustomobject][ordered]@{schemaVersion=1;kind='DEVFLEET_CAMPAIGN_E_M1_RESULT';status='PASS_DIAGNOSTIC';runId='unit';vmId='84b7d8b8-ee6c-4085-aa29-4b0adc316de2';payloadSha256=('a'*64);instanceName=$m1Name;ubuntuImage='24.04';ownerDeadlineUtc=$base.AddMinutes(20).ToString('o');producedAtUtc=$base.AddMinutes(16).ToString('o');multipassSha256=('b'*64);boundaryBefore=[ordered]@{activeTransactionPresent=$false;stageMarkerCount=0};preflight=[ordered]@{operation='baseline-inventory';outcome='PASS'};sequence=$m1;cleanup=$cleanupState;boundaryAfter=[ordered]@{activeTransactionPresent=$false;stageMarkerCount=0};primaryError='';productLifecycleStarted=$false;productProgressClaimed=$false}
Check (Assert-DevFleetCampaignEM1Result -Result $validM1 -ExpectedRunId 'unit' -ExpectedVmId ([guid]'84b7d8b8-ee6c-4085-aa29-4b0adc316de2') -ExpectedInstanceName $m1Name -ExpectedPayloadSha256 ('a'*64)) 'valid M1 result was rejected'
$badM1=$validM1|ConvertTo-Json -Depth 24|ConvertFrom-Json;$badM1.cleanup.status='UNVERIFIED';$rejected=$false;try{Assert-DevFleetCampaignEM1Result -Result $badM1 -ExpectedRunId 'unit' -ExpectedVmId ([guid]'84b7d8b8-ee6c-4085-aa29-4b0adc316de2') -ExpectedInstanceName $m1Name -ExpectedPayloadSha256 ('a'*64)|Out-Null}catch{$rejected=$true};Check $rejected 'M1 result accepted unverified cleanup'
$badM1=$validM1|ConvertTo-Json -Depth 24|ConvertFrom-Json;$badM1.productProgressClaimed=$true;$rejected=$false;try{Assert-DevFleetCampaignEM1Result -Result $badM1 -ExpectedRunId 'unit' -ExpectedVmId ([guid]'84b7d8b8-ee6c-4085-aa29-4b0adc316de2') -ExpectedInstanceName $m1Name -ExpectedPayloadSha256 ('a'*64)|Out-Null}catch{$rejected=$true};Check $rejected 'M1 result accepted fabricated product progress'
$script:m1Clock=$base;$script:m1Calls=[Collections.Generic.List[object]]::new();$timeoutM1={param($operation,$path,$arguments,$seconds,$owner)[void]$script:m1Calls.Add($operation);[pscustomobject]@{operation=$operation;outcome='TIMEOUT';exitCode=$null;pid=56;startedAtUtc=$base.ToString('o');finishedAtUtc=$base.AddSeconds(1).ToString('o');deadlineUtc=$base.AddMinutes(1).ToString('o');stdout='';stderr='bounded timeout';outputComplete=$true}}
$blockedM1=Invoke-DevFleetCampaignEMultipassM1Sequence -RunId 'unit' -InstanceName $m1Name -UbuntuImage '24.04' -MultipassPath 'C:\fixture\multipass.exe' -OwnerDeadlineUtc $base.AddMinutes(15) -NativeProbeProvider $timeoutM1 -ClockProvider {$script:m1Clock}
Check ([string]$blockedM1.status-ceq'BLOCKED'-and@($blockedM1.observations).Count-eq1-and@($script:m1Calls).Count-eq1-and-not[bool]$blockedM1.progress.launchAccepted) 'M1 launch timeout was mistaken for semantic progress or allowed later operations'
$script:m1Clock=$base;$malformedInfo={param($operation,$path,$arguments,$seconds,$owner)$start=$script:m1Clock;$script:m1Clock=$script:m1Clock.AddSeconds(1);[pscustomobject]@{operation=$operation;outcome='PASS';exitCode=0;pid=57;startedAtUtc=$start.ToString('o');finishedAtUtc=$script:m1Clock.ToString('o');deadlineUtc=([datetime]$owner).ToUniversalTime().ToString('o');stdout=if($operation-eq'info-running'){'{"info":{"wrong":{"state":"Running","ipv4":["10.0.0.2"]}}}'}else{''};stderr='';outputComplete=$true}}
$badInfoM1=Invoke-DevFleetCampaignEMultipassM1Sequence -RunId 'unit' -InstanceName $m1Name -UbuntuImage '24.04' -MultipassPath 'C:\fixture\multipass.exe' -OwnerDeadlineUtc $base.AddMinutes(15) -NativeProbeProvider $malformedInfo -ClockProvider {$script:m1Clock}
Check ([string]$badInfoM1.status-ceq'BLOCKED'-and-not[bool]$badInfoM1.progress.instanceRunning-and[string]$badInfoM1.primaryError-match'exact instance') 'M1 wrong-instance info masqueraded as readiness'
foreach($scriptName in @('Invoke-CampaignEMultipassM1.ps1','Invoke-CampaignEMultipassM1Worker.ps1')){$errors=$null;$tokens=$null;[Management.Automation.Language.Parser]::ParseFile((Join-Path (Split-Path -Parent $PSScriptRoot) $scriptName),[ref]$tokens,[ref]$errors)|Out-Null;Check ($errors.Count-eq0) "$scriptName has parser errors"}

Write-Host "PASS $count Campaign E Multipass diagnostic collector behavioral checks"
